language: python

matrix:
  include:
    - python: 3.8-dev
      env: TOXENV=coveralls
    - python: 3.6-dev
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
    - python: 3.8-dev
      env: TOXENV=py38
    - python: 3.10-dev
      env: TOXENV=py310

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev

install:
  - pip install -U --force-reinstall setuptools
  - pip install -U tox

script:
  - tox
